### ISSUE TITLE
Little mistakes in your code

### ISSUE THREAD

**Issue by ishaan-stohoven** [ai-honzik/simulated-annealing-in-cpp#1]
Hello, after inspecting your algorithm I found a couple of bugs and it is quite a slow solution. It seems that u did not consider the transition probabilities that result from the various for each edge. U didn't even use normalization under the Hilbert space's inner product using Dirac notation which can be easily achieved by plugging in diverse expressions for the Hamiltonian...

PS.: Would you like to work with me to develop a better and faster solution in JavaScript?

**Comment by dolejs-jan** [comment]
Hi @ishaan-stohoven, thanks for your interest. All you have stated may be true, as this was just a small experimental project, nothing else. Feel free to address the issues; however, I am not currently actively maintaining this repository, nor do I plan to in the near future.

Best regards
